baseURL: https://ameliaprzybyl.netlify.app/
languageCode: en-us
title: Amelia's website
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Learn more about me and my journey with data science
    # subtitle: |-
    #   A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
    #   AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Amelia
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: London Business School
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: aprzybyl.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: Available upon request
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Content and pictures by Amelia Przybyl
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      #- icon: fa-twitter
      #  label: Twitter
      #  url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100000623544290
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/amelcza
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/ameliaprzybyl
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/amelia-przybyl/
  image: 'banner.jpg'
  name: Amelia Przybyl
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Data analysis portfolio
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: portfolio website
    title: Amelia Przybyl
  tiles:
    enable: yes
    showcase:
      - image: me.jpg
        subtitle: Short bio
        title: About me
        url: blogs/about
      - image: money.jpg
        subtitle: Find out more about my career trajectory
        title: CV
        url: blogs/cv
      - image: airport.jpg
        subtitle: Lorem Etiam Nullam
        title: Magna
        url: blogs/magna
      - image: washington.jpg
        subtitle: Net approval ratings in 2022
        title: Biden's Approval
        url: blogs/biden
      - image: colombia.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Consequat
        url: blogs/ipsum
      - image: capadoccia.jpg
        subtitle: Feugiat Amet Tempus
        title: Etiam
        url: blogs/ipsum
  two:
    buttonText: See my work
    enable: yes
    subtitle: "I recently started studying Analytics and Management at London Business School, where I am starting my journey with Data Science. Here is a sneak peak into what I have been working on so far."
    title: Welcome
    url: blogs
