---
categories:
- ""
- ""
date: "2022-09-19"
description: ""
draft: false
image: colombia.jpg
keywords: ""
slug: youth
title: Youth Risk Behavior Surveillance
---



<div id="youth-risk-behavior-surveillance" class="section level1">
<h1>Youth Risk Behavior Surveillance</h1>
<div id="load-the-data" class="section level2">
<h2>Load the data</h2>
<pre class="r"><code>data(yrbss)
glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15, 1…
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;fema…
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, …
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;not&quot;…
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Africa…
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88, 1…
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71.2, …
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did not …
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did not…
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, 7, …
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;,…
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, 7, …
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;&lt;5&quot;…</code></pre>
<p>Check missing values, summary statistics of numerical variables, and a very rough histogram.</p>
<pre class="r"><code>skimr::skim(yrbss)</code></pre>
<table>
<caption>(#tab:feeling the data)Data summary</caption>
<tbody>
<tr class="odd">
<td align="left">Name</td>
<td align="left">yrbss</td>
</tr>
<tr class="even">
<td align="left">Number of rows</td>
<td align="left">13583</td>
</tr>
<tr class="odd">
<td align="left">Number of columns</td>
<td align="left">13</td>
</tr>
<tr class="even">
<td align="left">_______________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Column type frequency:</td>
<td align="left"></td>
</tr>
<tr class="even">
<td align="left">character</td>
<td align="left">8</td>
</tr>
<tr class="odd">
<td align="left">numeric</td>
<td align="left">5</td>
</tr>
<tr class="even">
<td align="left">________________________</td>
<td align="left"></td>
</tr>
<tr class="odd">
<td align="left">Group variables</td>
<td align="left">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table style="width:100%;">
<colgroup>
<col width="30%" />
<col width="12%" />
<col width="16%" />
<col width="4%" />
<col width="4%" />
<col width="7%" />
<col width="10%" />
<col width="13%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">min</th>
<th align="right">max</th>
<th align="right">empty</th>
<th align="right">n_unique</th>
<th align="right">whitespace</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">gender</td>
<td align="right">12</td>
<td align="right">1.00</td>
<td align="right">4</td>
<td align="right">6</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">grade</td>
<td align="right">79</td>
<td align="right">0.99</td>
<td align="right">1</td>
<td align="right">5</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hispanic</td>
<td align="right">231</td>
<td align="right">0.98</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">race</td>
<td align="right">2805</td>
<td align="right">0.79</td>
<td align="right">5</td>
<td align="right">41</td>
<td align="right">0</td>
<td align="right">5</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">helmet_12m</td>
<td align="right">311</td>
<td align="right">0.98</td>
<td align="right">5</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">text_while_driving_30d</td>
<td align="right">918</td>
<td align="right">0.93</td>
<td align="right">1</td>
<td align="right">13</td>
<td align="right">0</td>
<td align="right">8</td>
<td align="right">0</td>
</tr>
<tr class="odd">
<td align="left">hours_tv_per_school_day</td>
<td align="right">338</td>
<td align="right">0.98</td>
<td align="right">1</td>
<td align="right">12</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
<tr class="even">
<td align="left">school_night_hours_sleep</td>
<td align="right">1248</td>
<td align="right">0.91</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right">0</td>
<td align="right">7</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table style="width:100%;">
<colgroup>
<col width="22%" />
<col width="10%" />
<col width="15%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="5%" />
<col width="6%" />
<col width="6%" />
<col width="7%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">skim_variable</th>
<th align="right">n_missing</th>
<th align="right">complete_rate</th>
<th align="right">mean</th>
<th align="right">sd</th>
<th align="right">p0</th>
<th align="right">p25</th>
<th align="right">p50</th>
<th align="right">p75</th>
<th align="right">p100</th>
<th align="left">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">age</td>
<td align="right">77</td>
<td align="right">0.99</td>
<td align="right">16.16</td>
<td align="right">1.26</td>
<td align="right">12.00</td>
<td align="right">15.0</td>
<td align="right">16.00</td>
<td align="right">17.00</td>
<td align="right">18.00</td>
<td align="left">▁▂▅▅▇</td>
</tr>
<tr class="even">
<td align="left">height</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">1.69</td>
<td align="right">0.10</td>
<td align="right">1.27</td>
<td align="right">1.6</td>
<td align="right">1.68</td>
<td align="right">1.78</td>
<td align="right">2.11</td>
<td align="left">▁▅▇▃▁</td>
</tr>
<tr class="odd">
<td align="left">weight</td>
<td align="right">1004</td>
<td align="right">0.93</td>
<td align="right">67.91</td>
<td align="right">16.90</td>
<td align="right">29.94</td>
<td align="right">56.2</td>
<td align="right">64.41</td>
<td align="right">76.20</td>
<td align="right">180.99</td>
<td align="left">▆▇▂▁▁</td>
</tr>
<tr class="even">
<td align="left">physically_active_7d</td>
<td align="right">273</td>
<td align="right">0.98</td>
<td align="right">3.90</td>
<td align="right">2.56</td>
<td align="right">0.00</td>
<td align="right">2.0</td>
<td align="right">4.00</td>
<td align="right">7.00</td>
<td align="right">7.00</td>
<td align="left">▆▂▅▃▇</td>
</tr>
<tr class="odd">
<td align="left">strength_training_7d</td>
<td align="right">1176</td>
<td align="right">0.91</td>
<td align="right">2.95</td>
<td align="right">2.58</td>
<td align="right">0.00</td>
<td align="right">0.0</td>
<td align="right">3.00</td>
<td align="right">5.00</td>
<td align="right">7.00</td>
<td align="left">▇▂▅▂▅</td>
</tr>
</tbody>
</table>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<div id="distribution" class="section level3">
<h3>Distribution</h3>
<pre class="r"><code>weight &lt;- skimr::skim(yrbss) %&gt;%
  filter(skim_variable==&quot;weight&quot;)

ggplot(yrbss, aes(x=weight, na.rm=TRUE)) +
   geom_density() </code></pre>
<p><img src="/blogs/youth_files/figure-html/eda_on_weight-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>As we can see from the data, there are 1004 missing observations, the distribution is right skewed with its mean at 68kg and standard deviation at 17.</p>
</blockquote>
<pre class="r"><code>yrbss_clean &lt;- yrbss %&gt;% 
  drop_na(weight) %&gt;%
  drop_na(physically_active_7d) %&gt;%
  mutate(physical_3plus = ifelse(physically_active_7d &gt; 2, &quot;yes&quot;, &quot;no&quot;))

#count method
yrbss_cm &lt;- yrbss_clean %&gt;% 
  count(physical_3plus)
##calculating percentage active and inactive with count method
percentage_active_cm &lt;- yrbss_cm[2,2] / (yrbss_cm[1,2]+ yrbss_cm[2,2])
percentage_inactive_cm &lt;- 1 - percentage_active_cm

#group by and summarize method (gbsm)
yrbss_gbsm &lt;- yrbss_clean %&gt;% 
  group_by(physical_3plus) %&gt;%
  summarize(n = n())
##calculating percentage active and inactive with gbsm method
percentage_active_gbsm &lt;- yrbss_gbsm[2,2] / (yrbss_gbsm[1,2]+ yrbss_gbsm[2,2])
percentage_inactive_gbsm &lt;- 1 - percentage_active_gbsm</code></pre>
<blockquote>
<p>Above, we calculated the number of those that are not active for more than three days - 4022 - which constitutes 32.5% of the observations. The number is the same when using both the count method as well as the group by and summarise way.</p>
</blockquote>
</div>
<div id="ci-inactive-high-schoolers" class="section level3">
<h3>CI: inactive high schoolers</h3>
<p>the Confidence Interval for the population proportion of high schoolers that are NOT active 3 or more days per week</p>
<pre class="r"><code>sum = yrbss_gbsm[1,2] + yrbss_gbsm[2,2]
sd = sqrt((sum*percentage_inactive_cm)*(percentage_active_gbsm))
z = 1.96

#calculating confidence intervals
CI_low = percentage_inactive_cm-z*sd/sqrt(sum)
CI_high = percentage_inactive_cm+z*sd/sqrt(sum)

print(CI_low)</code></pre>
<pre><code>##        n
## 1 -0.593</code></pre>
<pre class="r"><code>print(CI_high)</code></pre>
<pre><code>##      n
## 1 1.24</code></pre>
<blockquote>
<p>The 95% confidence interval is between -0.593 and 1.24. This confidence interval fully covers the range from 0 to 1, which are the only results that we could observe in real life. This shows us that the data does not give us a reliable method of estimation for the population proportion of high schoolers that are not active for 3 or more days a week.</p>
</blockquote>
</div>
<div id="boxplot-physical_3plus-weight" class="section level3">
<h3>Boxplot: physical_3plus &amp; weight</h3>
<pre class="r"><code>yrbss_clean %&gt;%
  group_by(physical_3plus, weight) %&gt;%
  ggplot(aes(x = physical_3plus, y = weight, fill=physical_3plus)) +
  geom_boxplot() +
    labs(
    title = &quot;Boxplot of people active for more than 3 days vs weight&quot;,
    x = &quot;Are they active more than 3 times a week?&quot;,
    y = &quot;Weight&quot;)</code></pre>
<p><img src="/blogs/youth_files/figure-html/boxplot-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Based on this graph we can infer that there does not seem to be a relationship between weight and activity, which seems counterintuitive. This could point us to the fact that there is in fact another variable that influences your weight instead of physical activity, like for example consumption habits or genetics.</p>
</blockquote>
</div>
</div>
<div id="confidence-interval" class="section level2">
<h2>Confidence Interval</h2>
<pre class="r"><code>#Confidence interval - highly active
CI_highly_active &lt;- yrbss_clean %&gt;%
  filter(physical_3plus == &quot;yes&quot;) %&gt;%
  summarize(mean_weight = mean(weight, na.rm=TRUE),
            std_dev_weight = sd(weight, na.rm=TRUE),
            sample_size = n(),
            z = 1.96,
            CI_high = mean_weight + z * std_dev_weight / sqrt(sample_size),
            CI_low = mean_weight - z * std_dev_weight / sqrt(sample_size)
            )

print(CI_highly_active)</code></pre>
<pre><code>## # A tibble: 1 × 6
##   mean_weight std_dev_weight sample_size     z CI_high CI_low
##         &lt;dbl&gt;          &lt;dbl&gt;       &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
## 1        68.4           16.5        8342  1.96    68.8   68.1</code></pre>
<pre class="r"><code>#Confidence interval - not active
CI_not_active &lt;- yrbss_clean %&gt;%
  filter(physical_3plus == &quot;no&quot;) %&gt;%
  summarize(mean_weight = mean(weight, na.rm=TRUE),
            std_dev_weight = sd(weight, na.rm=TRUE),
            sample_size = n(),
            z = 1.96,
            CI_high = mean_weight + z * std_dev_weight / sqrt(sample_size),
            CI_low = mean_weight - z * std_dev_weight / sqrt(sample_size)
            )

print(CI_not_active)</code></pre>
<pre><code>## # A tibble: 1 × 6
##   mean_weight std_dev_weight sample_size     z CI_high CI_low
##         &lt;dbl&gt;          &lt;dbl&gt;       &lt;int&gt; &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
## 1        66.7           17.6        4022  1.96    67.2   66.1</code></pre>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<pre class="r"><code>t.test(weight ~ physical_3plus, data = yrbss_clean)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -5, df = 7479, p-value = 9e-08
## alternative hypothesis: true difference in means between group no and group yes is not equal to 0
## 95 percent confidence interval:
##  -2.42 -1.12
## sample estimates:
##  mean in group no mean in group yes 
##              66.7              68.4</code></pre>
<blockquote>
<p>The null hypothesis is that the true difference in means between group yes and no equals to zero, the alternative hypothesis is that it does not equal zero. As the p value is smaller than 0.05, we can reject the null hypothesis.</p>
</blockquote>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p>Initialize the test:</p>
<pre class="r"><code>obs_diff &lt;- yrbss_clean %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Simulate the test on the null distribution:</p>
<pre class="r"><code>null_dist &lt;- yrbss_clean %&gt;%
  # specify variables
  specify(weight ~ physical_3plus) %&gt;%
  
  # assume independence, i.e, there is no difference
  hypothesize(null = &quot;independence&quot;) %&gt;%
  
  # generate 1000 reps, of type &quot;permute&quot;
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  
  # calculate statistic of difference, namely &quot;diff in means&quot;
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Visualize the null distribution:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()</code></pre>
<p><img src="/blogs/youth_files/figure-html/unnamed-chunk-2-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>The p-value for the hypothesis test:</p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="/blogs/youth_files/figure-html/unnamed-chunk-3-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 × 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<blockquote>
<p>As the p value is on the right side of the observations, we can reject the null hypothesis.</p>
</blockquote>
</div>
</div>
